name: etcd-3
data-dir: /etcd3
initial-advertise-peer-urls: http://etcd-node3:2392
listen-peer-urls: http://0.0.0.0:2392
listen-client-urls: http://0.0.0.0:2371
advertise-client-urls: http://etcd-node3:2371
initial-cluster-token: etcd-cluster
initial-cluster: "etcd-1=http://etcd-node1:2390,etcd-2=http://etcd-node2:2391,etcd-3=http://etcd-node3:2392"
initial-cluster-state: new
