# Use the official etcd image as base
FROM quay.io/coreos/etcd:v3.4.0

# Set the working directory
WORKDIR /

# Copy the configuration file into the container
COPY etcd-config.yml /etc/etcd/etcd.yml

# Expose the peer and client ports
EXPOSE 2391 2369

# Command to run etcd with the custom configuration file
CMD ["etcd", "--config-file=/etc/etcd/etcd.yml"]
