name: etcd-1
data-dir: /etcd1
initial-advertise-peer-urls: http://etcd-node1:2390
listen-peer-urls: http://0.0.0.0:2390
listen-client-urls: http://0.0.0.0:2369
advertise-client-urls: http://etcd-node1:2369
initial-cluster-token: etcd-cluster
initial-cluster: "etcd-1=http://etcd-node1:2390,etcd-2=http://etcd-node2:2391,etcd-3=http://etcd-node3:2392"
initial-cluster-state: new
